# Generated by Django 4.0.6 on 2022-09-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="childsubunit",
            old_name="sub_unit",
            new_name="subunit",
        ),
    ]
