# Generated by Django 4.0.6 on 2022-10-18 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursereview_text'),
        ('account', '0006_child_total_points'),
        ('progress', '0002_rename_sub_unit_childsubunit_subunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCoursePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preview_progress', to='account.child')),
                ('course_preview', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_progress', to='course.coursepreview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
