# Generated by Django 4.0.6 on 2022-09-20 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_portaluser_otp_otp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
        migrations.AlterField(
            model_name="guardian",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardian",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
