# Generated by Django 4.0.6 on 2022-09-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_otp_options_alter_guardian_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_verified",
        ),
    ]
