# Generated by Django 4.0.6 on 2022-10-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0001_initial"),
        ("account", "0004_remove_otp_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="rewards",
            field=models.ManyToManyField(to="reward.reward"),
        ),
    ]
