# Generated by Django 4.0.6 on 2022-10-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_child_rewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="total_points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
