# Generated by Django 4.0.6 on 2022-09-07 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildAssessmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Public Identifier",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[("PR", "Pre assessment"), ("PO", "Post assessment")],
                        max_length=2,
                    ),
                ),
                (
                    "assessment_level",
                    models.CharField(
                        choices=[
                            ("1", "Level 1"),
                            ("2", "Level 2"),
                            ("3", "Level 3"),
                            ("4", "Level 4"),
                            ("5", "Level 5"),
                            ("6", "Level 6"),
                            ("7", "Level 7"),
                            ("8", "Level 8"),
                            ("9", "Level 9"),
                            ("10", "Level 10"),
                        ],
                        max_length=2,
                    ),
                ),
                ("attempts", models.IntegerField(null=True)),
                ("success", models.IntegerField(null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_log",
                        to="account.child",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_log",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_date"],
            },
        ),
    ]
