# Generated by Django 4.0.6 on 2022-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_alter_childassessmentlog_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childassessmentlog",
            name="question_type",
            field=models.CharField(
                choices=[("EQ", "Equations"), ("WP", "Word Problems")], max_length=10
            ),
        ),
    ]
