# Generated by Django 4.0.6 on 2022-09-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["created_date"]},
        ),
    ]
