# Generated by Django 4.0.6 on 2022-10-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subunit",
            name="link",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subunit",
            name="type",
            field=models.CharField(
                choices=[("GA", "Game"), ("VD", "Video"), ("EP", "Epaath")],
                default="EP",
                max_length=255,
            ),
        ),
    ]
