# Generated by Django 4.0.6 on 2022-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_subunit_link_subunit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subunit",
            name="link",
            field=models.URLField(max_length=255, null=True),
        ),
    ]
