# Generated by Django 4.0.6 on 2022-10-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_remove_lessonreview_lesson_delete_lessonpreview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursereview",
            name="type",
            field=models.CharField(
                choices=[
                    ("QZ", "Quiz"),
                    ("VD", "Video"),
                    ("EP", "Epaath"),
                    ("TX", "Text"),
                ],
                max_length=2,
            ),
        ),
    ]
