# Generated by Django 4.0.6 on 2022-10-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_alter_coursereview_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepreview",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
