# Generated by Django 4.0.6 on 2022-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_coursereview_completion_score_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subunit",
            options={},
        ),
        migrations.AlterField(
            model_name="subunit",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
