# Generated by Django 4.0.6 on 2022-10-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_subunit_options_alter_subunit_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
