# Generated by Django 4.0.6 on 2022-10-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursereview_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepreview',
            name='name',
            field=models.CharField(choices=[('Lesson Intro', 'Course Intro'), ('PRA', 'Pre Assessment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='coursepreview',
            name='type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Video', 'Video'), ('Epaath', 'Epaath')], max_length=255),
        ),
    ]
