# Generated by Django 4.0.6 on 2022-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_coursepreview_name_alter_coursepreview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='name',
            field=models.CharField(choices=[('Post Assessment', 'Post Assessment'), ("What's Next?", "What's Next?")], max_length=255),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Video', 'Video'), ('Epaath', 'Epaath'), ('Text', 'Text')], max_length=255),
        ),
    ]
